[package]
name = "catalyst-runtime-evm"
version = "0.1.0"
edition = "2021"
description = "Ethereum Virtual Machine runtime for Catalyst Network"
license = "MIT OR Apache-2.0"

[dependencies]
catalyst-core = { path = "../catalyst-core" }
# catalyst-storage = { path = "../catalyst-storage" }  # Comment out for now

# EVM implementation - use compatible versions without problematic features
revm = { version = "3.5", default-features = false, features = ["std", "serde"] }
revm-primitives = { version = "1.3", default-features = false, features = ["std", "serde"] }

# Ethereum types
ethereum-types = "0.14"
ethabi = "18.0"
keccak-hash = "0.10"

# Cryptographic functions
sha2 = "0.10"

# Async support
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Utilities
tracing = "0.1"
hex = "0.4"

[dev-dependencies]
tokio-test = "0.4"

[features]
default = []
# Optional features that can be enabled later
optimism = ["revm/optimism"]
# Remove kzg feature since it's not available
# kzg = ["revm/blst"]