[package]
name = "catalyst-utils"
version = "0.1.0"
edition = "2021"
description = "Utility functions for Catalyst Network"
license = "MIT OR Apache-2.0"

[dependencies]
# Error handling - ADD THIS
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
hex = "0.4"
rand = "0.8"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = []
full = []